name: Count Commits by User

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente a la medianoche UTC
  workflow_dispatch: # Permite la ejecución manual del workflow

jobs:
  count-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Count commits by user
      run: |
        git shortlog -s -n -e > commit_count.txt
        cat commit_count.txt

    - name: Commit results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add commit_count.txt
        git commit -m "Update commit count"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
